config/routes.rb
Rails.application.routes.draw do

  namespace :learning do
    get 'learning/home'
  end

  namespace :learning do
    get 'n5/index'
  end

  namespace :learning do
    get 'n5/show'
  end

  get 'static_pages/home'

  root 'static_pages#home'

  devise_for :users
  resources :users, only: [:index,:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kanjin1.rb
class Kanjin1 < ApplicationRecord
end

app/models/kanjin2.rb
class Kanjin2 < ApplicationRecord
end

app/models/kanjin3.rb
class Kanjin3 < ApplicationRecord
end

app/models/kanjin4.rb
class Kanjin4 < ApplicationRecord
end

app/models/kanjin5.rb
class Kanjin5 < ApplicationRecord
end

app/models/learningkanjin5.rb
class Learningkanjin5 < ApplicationRecord
	belongs_to :user, class_name: 'User', foreign_key: 'user_id'
	has_many :setkanji, class_name: 'Setkanjin5',foreign_key: 'set_id', primary_key: 'set_id'

	def kanjiset
		print (user.id)
		kanji =[]
		self.setkanji.each do |n|
			print "111___"
			print n
			kanji.push(n.kanji)
		end
		kanji
	end

end

app/models/setkanjin5.rb
class Setkanjin5 < ApplicationRecord
	has_one :kanji, class_name: 'Kanjin5', primary_key: 'kanji_id', foreign_key: 'id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    validates :name , presence: true

    has_many :learntSetKanjiN5, class_name: 'Learningkanjin5', foreign_key: 'user_id'

    def learntKanji
		kanji =[]
		self.learntSetKanjiN5.each do |n|
			n.kanjiset.each do |x|
				kanji.push(x)
			end	
		end
		kanji
	end

	def notLearnKanji
		kanji = self.learntKanji
		idLearntKanji = []
		kanji.each do |n|
			idLearntKanji.push(n.id)
			print n.id
		end
		if kanji.count > 0
			Kanjin5.where('id NOT IN (?)', idLearntKanji)
		else
			Kanjin5.all
		end
	end
end

app/models/vocabn1.rb
class Vocabn1 < ApplicationRecord
end

app/models/vocabn2.rb
class Vocabn2 < ApplicationRecord
end

app/models/vocabn3.rb
class Vocabn3 < ApplicationRecord
end

app/models/vocabn4.rb
class Vocabn4 < ApplicationRecord
end

app/models/vocabn5.rb
class Vocabn5 < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  	before_action :configure_permitted_parameters, if: :devise_controller?
	protected
		def configure_permitted_parameters
		# sign_upのときに、name, ageを許可する
		devise_parameter_sanitizer.permit :sign_up, keys: [:name, :age]
		# account_updateのときに、name,ageを許可する
		devise_parameter_sanitizer.permit :account_update, keys: [:name, :age]
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-default">
		<div class="navbar-brand">
			<%= link_to root_path do %>
			<%= image_tag("default/app_icon.png",:size => "30x30") %>
			<span class="app_name">JLPT Test</span>
			<% end %>
		</div>
		<ul class="right combo-btn hide-on-med-and-down">
			<li><%= link_to "Learning", learning_learning_home_path %></li>
			<% if signed_in? %>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" ><%= 'Hi, '+ current_user.name %> <span class="caret"></span></a>
					<ul class="dropdown-menu">
			            <li><%= link_to "Profile", current_user%></li>
			            <li><%= link_to "Log out", destroy_user_session_path , :method => :delete %></li>
		          </ul>
		        </li>
			<% else %>
		        <li><%= link_to "Log in", new_user_session_path %></li>
				<li><%= link_to "Sign up", new_user_registration_path %></li>
			<%end %>
		</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JlptTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_kanji.html.erb
<div>
	<h4><%= kanji.kanji %></h4>
</div>